[package]
name = "fractald-package-trigger"
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[dependencies]
fractald-control = { path = "../fractald-control" }
fractald-config = { path = "../fractald-config" }

[[bin]]
name = "fractald-package-trigger"
path = "src/main.rs"
